#Main settings
spring.main.banner-mode: console
spring.banner.location: classpath:app-banner.txt

spring.application.name: epayment-data-exchange
spring.jackson.serialization.indent_output: true
server.port: 8080

info:
  name: ${spring.application.name}
  description: Customs digital payment data exchange
  environment: ${spring.profiles.active}
  version: 0.0.1

#Proxy settings
proxy:
  #url: http://10.0.0.121:808/Olu4a/Olu4a.php?format=xml&articul=1181&amount=0&action=get_drivers_info&Ans=987&driver_id=1171&inputdate=200325135915
  url: http://109.74.70.51:5058/test.asp?command=getbalance&login=90121&sign=2a9e2419fec4437c303ec7579bd159f5
  PathKeyExchange: /uags/api/v1/exchange
  PathINQUIRY_EXCHANGERATE : /umts/iswitch/v1/inquiry/exchangerate
  PathCREDIT_VERIFY : /umts/iswitch/v1/creditverify
  PathPRIMERY_CREDIT : /umts/iswitch/v1/credit
  PathINQUIRY_MESSAGE : /umts/iswitch/v1/inquiry/message
  buffer-size: 10000000

# Certificate settings
cert:
  JWEKid : 1562032885962
  JWSKid : 379326499248820106081235601112670776256463256664
  DCAppId : 44560762

# logging
#logging.pattern.console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging:
  file:
    path: log
    name: log/app.log
    max-history: 365
    max-size: 10000000
  level:
    customs.payment.service: DEBUG
    com.zaxxer.hikari: WARN

debug: true


spring.output.ansi.enabled:  always